### ISSUE TITLE
Should we allow Access Tokens to be included in a TraT

### ISSUE THREAD

**Issue by PieterKas** [SGNL-ai/transaction-tokens#1]
Including Access Tokens may facilitate token theft.

**Comment by tulshi** [comment]
Access tokens are not included in the transaction tokens. They are only present in the request from the external endpoint workload to the Transaction Token Service.

**Comment by PieterKas** [comment]
Agreed, do we have text to preclude that now?

**Comment by PieterKas** [comment]
Issue addressed in security considerations.
