### ISSUE TITLE
Clarification on the aud claim in Txn-Token format and examples

### ISSUE THREAD

**Issue by appsdesh** [SGNL-ai/transaction-tokens#34]
> A Trust Domain must have an identifier that is used as the aud (audience) value in Txn-Tokens. The format of this identifier is a universal resource identifier. Each Trust Domain has exactly one Txn-Token Service

Let's clarify the `aud` claim in examples of [the Txn Token format section ](https://www.ietf.org/archive/id/draft-tulshibagwale-oauth-transaction-tokens-03.html#name-txn-token-format)

**Comment by PieterKas** [comment]
Decision: update the example.

Move context out, add aud.

**Comment by tulshi** [comment]
I believe this issue has been resolved.
